apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "demo-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "demo-chart.name" . }}
    spec:
      containers:
        - name: {{ include "demo-chart.name" . | trunc 63 | replace "." "-" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: "{{ .Values.containerPort }}"
