# File: .github/workflows/deploy-gke.yaml
name: Self-Hosted GKE Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      IMAGE_TAG: ${{ github.sha }}
      NAMESPACE: default   # Change if you want a custom namespace

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2️⃣ Authenticate with GCP using your secret
    - name: Authenticate GCP
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > /tmp/sa-key.json
        gcloud auth activate-service-account --key-file=/tmp/sa-key.json
        gcloud config set project $PROJECT_ID

    # 3️⃣ Terraform Init & Apply
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    # 4️⃣ Configure kubectl for GKE
    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    # 5️⃣ Build and Push Docker Image
    - name: Build Docker Image
      run: |
        docker build -t $DOCKER_REPO:$IMAGE_TAG .
        docker push $DOCKER_REPO:$IMAGE_TAG

    # 6️⃣ Create namespace if it doesn't exist
    - name: Ensure Namespace Exists
      run: |
        kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

    # 7️⃣ Deploy using Helm
    - name: Helm Upgrade / Install
      run: |
        helm upgrade --install my-app ./helm-chart \
          --namespace $NAMESPACE \
          --set image.repository=$DOCKER_REPO \
          --set image.tag=$IMAGE_TAG
