name: Terraform Apply (Self-Hosted)

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write GCP credentials
        run: |
          mkdir -p ${HOME}
          printf '%s' "${{ secrets.GCP_CREDENTIALS }}" > ${HOME}/gcp-key.json
          ls -l ${HOME}/gcp-key.json
          head -5 ${HOME}/gcp-key.json


      - name: Terraform init
        working-directory: ./infra
        run: terraform init

      - name: Terraform apply
        working-directory: ./infra
        run: terraform apply -auto-approve -var="project=test-project-1-466213" -var="zone=us-central1-a"
